// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum VideoPlayerPluginMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8_0000_0000_0000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }
  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true
    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Information passed to the platform view creation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformVideoViewCreationParams: Hashable, CustomStringConvertible {
  var playerId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformVideoViewCreationParams? {
    let playerId = pigeonVar_list[0] as! Int64

    return PlatformVideoViewCreationParams(
      playerId: playerId
    )
  }
  func toList() -> [Any?] {
    return [
      playerId
    ]
  }
  static func == (lhs: PlatformVideoViewCreationParams, rhs: PlatformVideoViewCreationParams)
    -> Bool
  {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.playerId, rhs.playerId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformVideoViewCreationParams")
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: playerId, hasher: &hasher)
  }

  public var description: String {
    return "PlatformVideoViewCreationParams(playerId: \(String(describing: playerId)))"
  }
}

/// Pigeon equivalent of video_player_avfoundation's FairPlayDrmConfiguration.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformFairPlayDrmConfiguration: Hashable, CustomStringConvertible {
  var certificateUri: String
  var licenseUri: String
  var licenseHeaders: [String: String]
  var contentId: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformFairPlayDrmConfiguration? {
    let certificateUri = pigeonVar_list[0] as! String
    let licenseUri = pigeonVar_list[1] as! String
    let licenseHeaders = pigeonVar_list[2] as! [String: String]
    let contentId: String? = nilOrValue(pigeonVar_list[3])

    return PlatformFairPlayDrmConfiguration(
      certificateUri: certificateUri,
      licenseUri: licenseUri,
      licenseHeaders: licenseHeaders,
      contentId: contentId
    )
  }
  func toList() -> [Any?] {
    return [
      certificateUri,
      licenseUri,
      licenseHeaders,
      contentId,
    ]
  }
  static func == (lhs: PlatformFairPlayDrmConfiguration, rhs: PlatformFairPlayDrmConfiguration)
    -> Bool
  {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPlayerPluginMessagesPigeonInternal.deepEquals(
      lhs.certificateUri, rhs.certificateUri)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.licenseUri, rhs.licenseUri)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.licenseHeaders, rhs.licenseHeaders)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.contentId, rhs.contentId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformFairPlayDrmConfiguration")
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: certificateUri, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: licenseUri, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: licenseHeaders, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: contentId, hasher: &hasher)
  }

  public var description: String {
    return
      "PlatformFairPlayDrmConfiguration(certificateUri: \(String(describing: certificateUri)), licenseUri: \(String(describing: licenseUri)), licenseHeaders: \(String(describing: licenseHeaders)), contentId: \(String(describing: contentId)))"
  }
}

/// Pigeon equivalent of video_player_platform_interface's VideoPlayerLiveOptions.
struct PlatformLiveConfiguration: Hashable, CustomStringConvertible {
  var targetOffsetMs: Int64
  var minOffsetMs: Int64
  var maxOffsetMs: Int64
  var minPlaybackSpeed: Double
  var maxPlaybackSpeed: Double
  var preferredForwardBufferDurationMs: Int64
  var minBufferDurationMs: Int64
  var maxBufferDurationMs: Int64
  var bufferForPlaybackMs: Int64
  var bufferForPlaybackAfterRebufferMs: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformLiveConfiguration? {
    let targetOffsetMs = pigeonVar_list[0] as! Int64
    let minOffsetMs = pigeonVar_list[1] as! Int64
    let maxOffsetMs = pigeonVar_list[2] as! Int64
    let minPlaybackSpeed = pigeonVar_list[3] as! Double
    let maxPlaybackSpeed = pigeonVar_list[4] as! Double
    let preferredForwardBufferDurationMs = pigeonVar_list[5] as! Int64
    let minBufferDurationMs = pigeonVar_list[6] as! Int64
    let maxBufferDurationMs = pigeonVar_list[7] as! Int64
    let bufferForPlaybackMs = pigeonVar_list[8] as! Int64
    let bufferForPlaybackAfterRebufferMs = pigeonVar_list[9] as! Int64

    return PlatformLiveConfiguration(
      targetOffsetMs: targetOffsetMs,
      minOffsetMs: minOffsetMs,
      maxOffsetMs: maxOffsetMs,
      minPlaybackSpeed: minPlaybackSpeed,
      maxPlaybackSpeed: maxPlaybackSpeed,
      preferredForwardBufferDurationMs: preferredForwardBufferDurationMs,
      minBufferDurationMs: minBufferDurationMs,
      maxBufferDurationMs: maxBufferDurationMs,
      bufferForPlaybackMs: bufferForPlaybackMs,
      bufferForPlaybackAfterRebufferMs: bufferForPlaybackAfterRebufferMs
    )
  }

  func toList() -> [Any?] {
    return [
      targetOffsetMs,
      minOffsetMs,
      maxOffsetMs,
      minPlaybackSpeed,
      maxPlaybackSpeed,
      preferredForwardBufferDurationMs,
      minBufferDurationMs,
      maxBufferDurationMs,
      bufferForPlaybackMs,
      bufferForPlaybackAfterRebufferMs,
    ]
  }

  static func == (lhs: PlatformLiveConfiguration, rhs: PlatformLiveConfiguration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.targetOffsetMs, rhs.targetOffsetMs)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.minOffsetMs, rhs.minOffsetMs)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.maxOffsetMs, rhs.maxOffsetMs)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.minPlaybackSpeed, rhs.minPlaybackSpeed)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.maxPlaybackSpeed, rhs.maxPlaybackSpeed)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.preferredForwardBufferDurationMs, rhs.preferredForwardBufferDurationMs)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.minBufferDurationMs, rhs.minBufferDurationMs)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.maxBufferDurationMs, rhs.maxBufferDurationMs)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.bufferForPlaybackMs, rhs.bufferForPlaybackMs)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.bufferForPlaybackAfterRebufferMs, rhs.bufferForPlaybackAfterRebufferMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformLiveConfiguration")
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: targetOffsetMs, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: minOffsetMs, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: maxOffsetMs, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: minPlaybackSpeed, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: maxPlaybackSpeed, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: preferredForwardBufferDurationMs, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: minBufferDurationMs, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: maxBufferDurationMs, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: bufferForPlaybackMs, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: bufferForPlaybackAfterRebufferMs, hasher: &hasher)
  }

  public var description: String {
    return "PlatformLiveConfiguration(targetOffsetMs: \(String(describing: targetOffsetMs)), minOffsetMs: \(String(describing: minOffsetMs)), maxOffsetMs: \(String(describing: maxOffsetMs)), minPlaybackSpeed: \(String(describing: minPlaybackSpeed)), maxPlaybackSpeed: \(String(describing: maxPlaybackSpeed)), preferredForwardBufferDurationMs: \(String(describing: preferredForwardBufferDurationMs)), minBufferDurationMs: \(String(describing: minBufferDurationMs)), maxBufferDurationMs: \(String(describing: maxBufferDurationMs)), bufferForPlaybackMs: \(String(describing: bufferForPlaybackMs)), bufferForPlaybackAfterRebufferMs: \(String(describing: bufferForPlaybackAfterRebufferMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CreationOptions: Hashable, CustomStringConvertible {
  var uri: String
  var isLive: Bool? = nil
  var allowPictureInPicture: Bool? = nil
  var httpHeaders: [String: String]
  var fairPlayDrm: PlatformFairPlayDrmConfiguration? = nil
  var liveConfiguration: PlatformLiveConfiguration? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreationOptions? {
    let uri = pigeonVar_list[0] as! String
    let isLive: Bool? = nilOrValue(pigeonVar_list[1])
    let allowPictureInPicture: Bool? = nilOrValue(pigeonVar_list[2])
    let httpHeaders = pigeonVar_list[3] as! [String: String]
    let fairPlayDrm: PlatformFairPlayDrmConfiguration? = nilOrValue(pigeonVar_list[4])
    let liveConfiguration: PlatformLiveConfiguration? = nilOrValue(pigeonVar_list[5])

    return CreationOptions(
      uri: uri,
      isLive: isLive,
      allowPictureInPicture: allowPictureInPicture,
      httpHeaders: httpHeaders,
      fairPlayDrm: fairPlayDrm,
      liveConfiguration: liveConfiguration
    )
  }
  func toList() -> [Any?] {
    return [
      uri,
      httpHeaders,
      fairPlayDrm,
      isLive,
      allowPictureInPicture,
      liveConfiguration,
    ]
  }
  static func == (lhs: CreationOptions, rhs: CreationOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.httpHeaders, rhs.httpHeaders)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.fairPlayDrm, rhs.fairPlayDrm)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.isLive, rhs.isLive)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.allowPictureInPicture, rhs.allowPictureInPicture)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.liveConfiguration, rhs.liveConfiguration)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreationOptions")
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: httpHeaders, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: fairPlayDrm, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: isLive, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: allowPictureInPicture, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: liveConfiguration, hasher: &hasher)
  }

  public var description: String {
    return
      "CreationOptions(uri: \(String(describing: uri)), httpHeaders: \(String(describing: httpHeaders)), fairPlayDrm: \(String(describing: fairPlayDrm)), isLive: \(String(describing: isLive)), allowPictureInPicture: \(String(describing: allowPictureInPicture)), liveConfiguration: \(String(describing: liveConfiguration)))"
  }
}
/// Generated class from Pigeon that represents data sent in messages.
struct TexturePlayerIds: Hashable, CustomStringConvertible {
  var playerId: Int64
  var textureId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TexturePlayerIds? {
    let playerId = pigeonVar_list[0] as! Int64
    let textureId = pigeonVar_list[1] as! Int64

    return TexturePlayerIds(
      playerId: playerId,
      textureId: textureId
    )
  }
  func toList() -> [Any?] {
    return [
      playerId,
      textureId,
    ]
  }
  static func == (lhs: TexturePlayerIds, rhs: TexturePlayerIds) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.playerId, rhs.playerId)
      && VideoPlayerPluginMessagesPigeonInternal.deepEquals(lhs.textureId, rhs.textureId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TexturePlayerIds")
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: playerId, hasher: &hasher)
    VideoPlayerPluginMessagesPigeonInternal.deepHash(value: textureId, hasher: &hasher)
  }

  public var description: String {
    return
      "TexturePlayerIds(playerId: \(String(describing: playerId)), textureId: \(String(describing: textureId)))"
  }
}

private class VideoPlayerPluginMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PlatformVideoViewCreationParams.fromList(self.readValue() as! [Any?])
    case 130:
      return PlatformFairPlayDrmConfiguration.fromList(self.readValue() as! [Any?])
    case 131:
      return PlatformLiveConfiguration.fromList(self.readValue() as! [Any?])
    case 132:
      return CreationOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return TexturePlayerIds.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VideoPlayerPluginMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformVideoViewCreationParams {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformFairPlayDrmConfiguration {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformLiveConfiguration {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CreationOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? TexturePlayerIds {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VideoPlayerPluginMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VideoPlayerPluginMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VideoPlayerPluginMessagesPigeonCodecWriter(data: data)
  }
}

class VideoPlayerPluginMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VideoPlayerPluginMessagesPigeonCodec(
    readerWriter: VideoPlayerPluginMessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AVFoundationVideoPlayerApi {
  func initialize() throws
  func createPlatformViewPlayer(options params: CreationOptions) throws -> Int64
  func createTexturePlayer(options creationOptions: CreationOptions) throws -> TexturePlayerIds
  func setMixWithOthers(_ mixWithOthers: Bool) throws
  func fileURLForAsset(name asset: String, package: String?) throws -> String?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AVFoundationVideoPlayerApiSetup {
  static var codec: FlutterStandardMessageCodec { VideoPlayerPluginMessagesPigeonCodec.shared }
  /// Sets up an instance of `AVFoundationVideoPlayerApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: AVFoundationVideoPlayerApi?,
    messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.initialize\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        do {
          try api.initialize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let createForPlatformViewChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.createForPlatformView\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createForPlatformViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! CreationOptions
        do {
          let result = try api.createPlatformViewPlayer(options: paramsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createForPlatformViewChannel.setMessageHandler(nil)
    }
    let createForTextureViewChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.createForTextureView\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createForTextureViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let creationOptionsArg = args[0] as! CreationOptions
        do {
          let result = try api.createTexturePlayer(options: creationOptionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createForTextureViewChannel.setMessageHandler(nil)
    }
    let setMixWithOthersChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setMixWithOthers\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMixWithOthersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mixWithOthersArg = args[0] as! Bool
        do {
          try api.setMixWithOthers(mixWithOthersArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMixWithOthersChannel.setMessageHandler(nil)
    }
    let getAssetUrlChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.getAssetUrl\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAssetUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetArg = args[0] as! String
        let packageArg: String? = nilOrValue(args[1])
        do {
          let result = try api.fileURLForAsset(name: assetArg, package: packageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAssetUrlChannel.setMessageHandler(nil)
    }
  }
}
